### ISSUE TITLE
Build failed with v2.074.0

### ISSUE THREAD

**Issue by EmTee70** [buggins/dlangide#362]
I got:
dlangui 0.9.173: building configuration "default"...
../../.dub/packages/dlangui-0.9.173/dlangui/src/dlangui/widgets/lists.d(1407,16): Error: module stopwatch is in file 'std/datetime/stopwatch.d' which cannot be read
import path[0] = ../../.dub/packages/dlangui-0.9.173/dlangui/3rdparty

Using:  dmd --version DMD64 D Compiler v2.074.0 on Ubuntu 16.04.

But after update to 2.077 compilation worked.

So you just need to update your readme  entry: **Needs DMD 2.066.1 or newer to build.**

**Comment by buggins** [comment]
Added DMD 2.0.77 requirement
But didn't find 2.066 mentioned in it.

**Comment by EmTee70** [comment]
I found it here:  https://github.com/buggins/dlangide
Just search in your browser for 66
I paste the context here:
**Building DlangIDE**

Build and run with DUB:

git clone https://github.com/buggins/dlangide.git
cd dlangide
dub run

If you see build errors, try to upgrade dependencies:

    dub clean-caches
dub upgrade --force-remove
dub build --force

_Needs DMD 2.066.1 or newer to build._

HINT: Try to open sample project Tetris, from workspaces/tetris with DlangIDE.
