### ISSUE TITLE
Does not build on Ubuntu 18.04.1 - Neither v.0.8.12 nor v0.8.5

### ISSUE THREAD

**Issue by jradxl** [buggins/dlangide#384]
Try 1, using:-
dub fetch dlangide
dub run --build=release dlangide

Try 2, using:-
git clone --recursive https://github.com/buggins/dlangide.git
dub build

Try 3, using:-
dub clean-caches
dub upgrade --force-remove
dub build --force

First error is 
../../.dub/packages/dlangui-0.9.178/dlangui/3rdparty/dimage/stream.d(226,16): Error: module `string` is in file 'std/c/string.d' which cannot be read
Which I can fix by editing Line 226 from import std.c.string;  to  import core.stdc.string;

But a further build fails on (possibly) a lot of Deprecation errors, which I have no idea about.

Anyone any suggestions
Thanks

**Comment by anispider** [comment]
I ran into this same issue (on Windows 10 & a fresh Linux Mint 19 install)

I was able to get around it (at least on Linux, haven't tried Windows yet), by:

1. making that same edit to stream.d
2. using ldc as the compiler, instead of dmd. 

try: (for Ubuntu and derivatives)
sudo apt-get install ldc
dub run --build=release dlangide --compiler=ldc2

I still got a ton of deprecation warnings in the build, but it worked. 

FYI, it looks like either dub or dmd might be crashing in the default command line. You can se a bit more information if you add --vverbose (yes with 2 v's ) to your dub command line. it looks like dub is hitting an internal exception during the build process.

**Comment by jradxl** [comment]
Hi,
I've just found same...  A dmd compiler failure, with:-

dub build --verbose -f -b release

FAIL .dub/build/default-release-linux.posix-x86_64-dmd_2082-822726CD45D593565748BD53F4E8A8BD/ dlangide executable
/usr/bin/dmd failed with exit code 1.

I'll try the ldc complier as you suggest.
Thanks

**Comment by jradxl** [comment]
Thanks, built and running now.
Thanks for writing up the commands
First time with D, pity it isn't more widely promoted, as I can't see why Golang would be better!
I'm feeling all nostalgic for Zorland C

**Comment by anispider** [comment]
I agree completely! I really like D, though I have not used it extensively. I have used Go a little professionally, and while it's ok, I don't think it deserves quite as much hype as it gets.

**Comment by MateiIonutEduard** [comment]
Yeah! I've used many programming languages, such C/C++/C#/Java/Python. This project is somewhat unsafe, because the D compiler is updated continuously. Maybe in future versions something concrete can be done. I think nothing can be done, however I started a IDE program made in C# that has pretty much everything you need at the moment, except for the debugger.
I don't know how to program a debugger, thus, I will convert DCD's debugger from Dlang to C# and build it.
